# ~/environment/sam-app/buildspec.yml

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - apt-get install -y jq
      - pip3 install --upgrade aws-sam-cli
      - pip3 install --upgrade awscli
      - sam --version
      # Installing project dependencies
      - cd orders/src
      - npm install
  
  pre_build:
    commands:

  #     # Run tests, lint scripts or any other pre-build checks.
  #     - npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - cd ..
  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      - sam package -t db.yml --s3-bucket $PACKAGE_BUCKET --output-template-file db-packaged.yml
      - sam package -t app.yml --s3-bucket $PACKAGE_BUCKET --output-template-file app-packaged.yml

      # - aws s3 copy s3://$PACKAGE_BUCKET/paramaters/$Environment/boppis-order-app.json .
      # - aws s3 copy s3://$PACKAGE_BUCKET/paramaters/$Environment/boppis-db-app.json .

artifacts:
  discard-paths: yes
  files:
    # List of local artifacts that will be passed down the pipeline
    - orders/db-packaged.yml
    - orders/app-packaged.yml
    - orders/parameters/$ENV/boppis-order-app.json
    - orders/parameters/$ENV/boppis-order-db.json
